name: simple_media
description: "A simple Flutter plugin to play Audio content. Supports background playback."
version: 0.1.1
homepage: hevsoft.go.ro

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.hevsoft.media
        pluginClass: MediaPlugin #If you get errors, make sure this class exists on Android
      ios:
        pluginClass: AudioPlayerPlugin
